version: '3.3'


services:

  php_handler:
    build:
      context: ./php/
    volumes:
      - ./website:/website
    restart: always
    depends_on:
      - mysqldb
    links:
      - mysqldb

  web_server:
    image: nginx
    volumes:
      - ./website:/website
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php_handler
    depends_on:
      - php_handler
    restart: always

  cache_server:
    image: varnish
    environment:
      - VARNISH_PORT
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
      - ./varnish/varnish:/etc/default/varnish
    depends_on:
     - web_server
    links:
     - web_server
    ports:
      - ${VARNISH_PORT}:${VARNISH_PORT}
    restart: always

  # it's better to disable or restrict access to phpmyadmin in your
  # production environment
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "5555:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysqldb
    restart: always
    depends_on:
        - mysqldb

  mysqldb:
    build:
      context: ./mysql
    restart: always
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data: